# Generated by Django 2.2.3 on 2019-07-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankOperation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='address',
            field=models.CharField(default='adress', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='bank_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='branch',
            field=models.CharField(default='branch', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='city',
            field=models.CharField(default='city', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='district',
            field=models.CharField(default='district', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='state',
            field=models.CharField(default='state', max_length=20),
            preserve_default=False,
        ),
    ]
