# Generated by Django 2.2.3 on 2019-07-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankOperation', '0002_auto_20190721_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='address',
            field=models.CharField(max_length=195),
        ),
        migrations.AlterField(
            model_name='branches',
            name='branch',
            field=models.CharField(max_length=74),
        ),
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='branches',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='branches',
            name='state',
            field=models.CharField(max_length=26),
        ),
    ]
